package IHM;

import com.mycompany.gestioncatalogue.CategorieProduit;
import com.mycompany.gestioncatalogue.ConnexionDAO;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Elyes - Alix
 */
public class IHM_Catalogue extends javax.swing.JFrame{
    
    
    public IHM_Catalogue()
    { 
        initComponents();
        ConnexionDAO.Connexion(); 
        affecterCat(); 
        affecterTotalSsCat();
        PanResult.setVisible(false);
    }  
    
    private void affecterCat(){
        Object[] tabCat = CategorieProduit.getCategorie().toArray();
        for(int i =0;i<tabCat.length;i++){
            cb_Cat.addItem((String)tabCat[i]);
            cb_Categ.addItem((String)tabCat[i]);
        }
    }       
    
    private void affecterTotalSsCat(){
        Object[] tabCat = CategorieProduit.getTotalSsCategorie().toArray();
        for(int i =0;i<tabCat.length;i++){
            cb_ssCateg.addItem((String)tabCat[i]);
        }
    }      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        tabPCPC = new javax.swing.JTabbedPane();
        PanelProduits = new javax.swing.JPanel();
        lbl_Search = new javax.swing.JLabel();
        PanSearch = new javax.swing.JPanel();
        cb_ssCat = new javax.swing.JComboBox<>();
        lbl_ssCat = new javax.swing.JLabel();
        lbl_Libelle = new javax.swing.JLabel();
        lbl_Cat = new javax.swing.JLabel();
        tf_Libelle = new javax.swing.JTextField();
        cb_Cat = new javax.swing.JComboBox<>();
        PannButtonSearch = new javax.swing.JPanel();
        Button_effacer = new javax.swing.JButton();
        Button_Search = new javax.swing.JButton();
        PanResult = new javax.swing.JPanel();
        lbl_ID = new javax.swing.JLabel();
        tf_ID = new javax.swing.JTextField();
        lbl_Cate = new javax.swing.JLabel();
        cb_cat = new javax.swing.JComboBox<>();
        lbl_prod = new javax.swing.JLabel();
        tf_prod = new javax.swing.JTextField();
        cb_ssCat1 = new javax.swing.JComboBox<>();
        lbl_ssCat1 = new javax.swing.JLabel();
        lbl_description = new javax.swing.JLabel();
        Scroll_description = new javax.swing.JScrollPane();
        ta_description = new javax.swing.JTextArea();
        lbl_prix = new javax.swing.JLabel();
        lbl_promo = new javax.swing.JLabel();
        Radio_oui = new javax.swing.JRadioButton();
        Radio_non = new javax.swing.JRadioButton();
        tf_prix = new javax.swing.JTextField();
        lbl_prix_Reduit = new javax.swing.JLabel();
        tf_prixReduit = new javax.swing.JTextField();
        lbl_stock = new javax.swing.JLabel();
        tf_stock = new javax.swing.JTextField();
        lbl_alerte = new javax.swing.JLabel();
        tf_alerte = new javax.swing.JTextField();
        lbl_Marque = new javax.swing.JLabel();
        tf_Marque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_fournisseur = new javax.swing.JTextField();
        lbl_ImageCat = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbl_ImageSsCat = new javax.swing.JLabel();
        tf_ImageCat = new java.awt.TextField();
        tf_ImageSsCat = new java.awt.TextField();
        jPanAjouter = new javax.swing.JPanel();
        jButAdd = new javax.swing.JButton();
        PanelCat = new javax.swing.JPanel();
        lbl_cat = new javax.swing.JLabel();
        PanSearchCat = new javax.swing.JPanel();
        lbl_categ = new javax.swing.JLabel();
        cb_Categ = new javax.swing.JComboBox<>();
        lbl_ssCateg = new javax.swing.JLabel();
        cb_ssCateg = new javax.swing.JComboBox<>();
        PannButtonSearch1 = new javax.swing.JPanel();
        Button_effacer1 = new javax.swing.JButton();
        Button_Search1 = new javax.swing.JButton();
        Button_effacer2 = new javax.swing.JButton();
        Button_Search2 = new javax.swing.JButton();
        PanResCat = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableauCat = new javax.swing.JTable();
        PannCreerModiSuppr = new javax.swing.JPanel();
        ButCreerCat = new javax.swing.JButton();
        ButModifCat = new javax.swing.JButton();
        ButSupCat = new javax.swing.JButton();
        ButCreerSsCat = new javax.swing.JButton();
        ButModifSsCat = new javax.swing.JButton();
        ButSupSsCat = new javax.swing.JButton();
        PanelPromo = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbl_SearchPromo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        PanelClients = new javax.swing.JPanel();
        lbl_cust = new javax.swing.JLabel();
        PanSearchClient = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMGestCat = new javax.swing.JMenuItem();
        jMGestProm = new javax.swing.JMenuItem();
        jMGestClient = new javax.swing.JMenuItem();
        jMCharger = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMSave = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuQuitter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuVersion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Croquettes A Temps Software (CATS)");
        setBackground(new java.awt.Color(0, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbl_Search.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lbl_Search.setText("Ajouter ou Rechercher un Produit");

        PanSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cb_ssCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_ssCatItemStateChanged(evt);
            }
        });
        cb_ssCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ssCatActionPerformed(evt);
            }
        });

        lbl_ssCat.setText("Sous-Catégorie :");

        lbl_Libelle.setText("Libellé :");

        lbl_Cat.setText("Catégorie :");

        cb_Cat.setToolTipText("");
        cb_Cat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_CatItemStateChanged(evt);
            }
        });
        cb_Cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CatActionPerformed(evt);
            }
        });

        Button_effacer.setText("Effacer");
        Button_effacer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_effacerMouseClicked(evt);
            }
        });
        Button_effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_effacerActionPerformed(evt);
            }
        });

        Button_Search.setText("Rechercher");
        Button_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SearchMouseClicked(evt);
            }
        });
        Button_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PannButtonSearchLayout = new javax.swing.GroupLayout(PannButtonSearch);
        PannButtonSearch.setLayout(PannButtonSearchLayout);
        PannButtonSearchLayout.setHorizontalGroup(
            PannButtonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannButtonSearchLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Button_Search)
                .addGap(26, 26, 26)
                .addComponent(Button_effacer)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PannButtonSearchLayout.setVerticalGroup(
            PannButtonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannButtonSearchLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PannButtonSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_effacer)
                    .addComponent(Button_Search))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanSearchLayout = new javax.swing.GroupLayout(PanSearch);
        PanSearch.setLayout(PanSearchLayout);
        PanSearchLayout.setHorizontalGroup(
            PanSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSearchLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(PanSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanSearchLayout.createSequentialGroup()
                        .addComponent(lbl_Cat)
                        .addGap(18, 18, 18)
                        .addComponent(cb_Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ssCat)
                        .addGap(18, 18, 18)
                        .addComponent(cb_ssCat, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanSearchLayout.createSequentialGroup()
                        .addComponent(lbl_Libelle)
                        .addGap(35, 35, 35)
                        .addComponent(tf_Libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanSearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PannButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        PanSearchLayout.setVerticalGroup(
            PanSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSearchLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(PanSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanSearchLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PanSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cat)
                            .addComponent(cb_Cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_ssCat)
                            .addComponent(cb_ssCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_Libelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_Libelle)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PannButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanResult.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_ID.setText("ID :");

        lbl_Cate.setText("Catégorie :");

        cb_cat.setAutoscrolls(true);
        cb_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_catActionPerformed(evt);
            }
        });

        lbl_prod.setText("Libellé Produit : ");

        tf_prod.setToolTipText("");

        lbl_ssCat1.setText("Sous-Catégorie :");

        lbl_description.setText("Description :");

        ta_description.setColumns(20);
        ta_description.setRows(5);
        Scroll_description.setViewportView(ta_description);

        lbl_prix.setText("Prix :");

        lbl_promo.setText("Promotion :");

        Radio_oui.setText("Oui");
        Radio_oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_ouiActionPerformed(evt);
            }
        });

        Radio_non.setText("Non");

        lbl_prix_Reduit.setText("Prix Réduit :");

        tf_prixReduit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_prixReduitActionPerformed(evt);
            }
        });

        lbl_stock.setText("Quantité en stock :");

        lbl_alerte.setText("Seuil d'alerte :");

        lbl_Marque.setText("Marque :");

        jLabel5.setText("ID Fournisseur :");

        tf_fournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fournisseurActionPerformed(evt);
            }
        });

        jButton6.setText("Supprimer le produit");

        jButton5.setText("Modifier le produit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lbl_ImageCatLayout = new javax.swing.GroupLayout(lbl_ImageCat);
        lbl_ImageCat.setLayout(lbl_ImageCatLayout);
        lbl_ImageCatLayout.setHorizontalGroup(
            lbl_ImageCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_ImageCatLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(155, 155, 155))
        );
        lbl_ImageCatLayout.setVerticalGroup(
            lbl_ImageCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lbl_ImageCatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lbl_ImageCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLabel9.setText("Image Catégorie :");

        lbl_ImageSsCat.setText("Image Sous-Catégorie :");

        tf_ImageCat.setPreferredSize(new java.awt.Dimension(8, 24));
        tf_ImageCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ImageCatActionPerformed(evt);
            }
        });

        tf_ImageSsCat.setPreferredSize(new java.awt.Dimension(8, 24));
        tf_ImageSsCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ImageSsCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanResultLayout = new javax.swing.GroupLayout(PanResult);
        PanResult.setLayout(PanResultLayout);
        PanResultLayout.setHorizontalGroup(
            PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanResultLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanResultLayout.createSequentialGroup()
                        .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_prod)
                            .addComponent(lbl_description)
                            .addComponent(lbl_prix))
                        .addGap(18, 18, 18)
                        .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanResultLayout.createSequentialGroup()
                                .addComponent(tf_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanResultLayout.createSequentialGroup()
                                        .addGap(110, 110, 110)
                                        .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(PanResultLayout.createSequentialGroup()
                                                .addComponent(lbl_alerte)
                                                .addGap(8, 8, 8)
                                                .addComponent(tf_alerte, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanResultLayout.createSequentialGroup()
                                                .addComponent(lbl_prix_Reduit)
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_prixReduit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanResultLayout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_ssCat1)
                                            .addComponent(lbl_Marque))
                                        .addGap(140, 140, 140))))
                            .addComponent(Scroll_description, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)))
                    .addGroup(PanResultLayout.createSequentialGroup()
                        .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanResultLayout.createSequentialGroup()
                                .addComponent(lbl_ID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_Cate))
                            .addGroup(PanResultLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanResultLayout.createSequentialGroup()
                                        .addComponent(lbl_stock)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanResultLayout.createSequentialGroup()
                                        .addComponent(lbl_promo)
                                        .addGap(27, 27, 27)
                                        .addComponent(Radio_oui)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Radio_non)))))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanResultLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_Marque)
                            .addComponent(cb_ssCat1, 0, 122, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanResultLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_ImageCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(PanResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ImageSsCat)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_ImageCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_ImageSsCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        PanResultLayout.setVerticalGroup(
            PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ID)
                    .addComponent(tf_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Cate)
                    .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ssCat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ssCat1))
                .addGap(18, 18, 18)
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_prod)
                    .addComponent(tf_prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Marque)
                    .addComponent(tf_Marque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanResultLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_description))
                    .addGroup(PanResultLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Scroll_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_prix)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_promo)
                        .addComponent(Radio_oui)
                        .addComponent(Radio_non)
                        .addComponent(lbl_prix_Reduit)
                        .addComponent(tf_prixReduit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_prix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanResultLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_fournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_stock)
                            .addComponent(tf_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanResultLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_alerte)
                            .addComponent(tf_alerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_ImageCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGroup(PanResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanResultLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_ImageSsCat))
                    .addGroup(PanResultLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_ImageSsCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(lbl_ImageCat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanAjouter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButAdd.setText("Ajouter un produit");
        jButAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButAddMouseClicked(evt);
            }
        });
        jButAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanAjouterLayout = new javax.swing.GroupLayout(jPanAjouter);
        jPanAjouter.setLayout(jPanAjouterLayout);
        jPanAjouterLayout.setHorizontalGroup(
            jPanAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanAjouterLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jButAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanAjouterLayout.setVerticalGroup(
            jPanAjouterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanAjouterLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelProduitsLayout = new javax.swing.GroupLayout(PanelProduits);
        PanelProduits.setLayout(PanelProduitsLayout);
        PanelProduitsLayout.setHorizontalGroup(
            PanelProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProduitsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanAjouter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelProduitsLayout.createSequentialGroup()
                        .addComponent(lbl_Search)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelProduitsLayout.setVerticalGroup(
            PanelProduitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProduitsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );

        tabPCPC.addTab("Produits", PanelProduits);

        lbl_cat.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lbl_cat.setText("Rechercher une Catégorie");

        PanSearchCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_categ.setText("Catégorie :");

        cb_Categ.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_CategItemStateChanged(evt);
            }
        });
        cb_Categ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_CategActionPerformed(evt);
            }
        });

        lbl_ssCateg.setText("Sous-Catégorie :");

        cb_ssCateg.setToolTipText("");

        Button_effacer1.setText("Effacer");

        Button_Search1.setText("Rechercher");
        Button_Search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Search1ActionPerformed(evt);
            }
        });

        Button_effacer2.setText("Effacer");

        Button_Search2.setText("Rechercher");
        Button_Search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Search2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PannButtonSearch1Layout = new javax.swing.GroupLayout(PannButtonSearch1);
        PannButtonSearch1.setLayout(PannButtonSearch1Layout);
        PannButtonSearch1Layout.setHorizontalGroup(
            PannButtonSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannButtonSearch1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PannButtonSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Search2)
                    .addComponent(Button_Search1))
                .addGap(44, 44, 44)
                .addGroup(PannButtonSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_effacer1)
                    .addComponent(Button_effacer2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        PannButtonSearch1Layout.setVerticalGroup(
            PannButtonSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannButtonSearch1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(PannButtonSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_effacer1)
                    .addComponent(Button_Search1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PannButtonSearch1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Search2)
                    .addComponent(Button_effacer2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanSearchCatLayout = new javax.swing.GroupLayout(PanSearchCat);
        PanSearchCat.setLayout(PanSearchCatLayout);
        PanSearchCatLayout.setHorizontalGroup(
            PanSearchCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSearchCatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanSearchCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_ssCateg)
                    .addComponent(lbl_categ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanSearchCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_Categ, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ssCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PannButtonSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        PanSearchCatLayout.setVerticalGroup(
            PanSearchCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSearchCatLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(PanSearchCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_categ)
                    .addComponent(cb_Categ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanSearchCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ssCateg)
                    .addComponent(cb_ssCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanSearchCatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PannButtonSearch1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanResCat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TableauCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "idCategorie", "idSousCategorie", "idProduit", "quantite"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableauCat);

        ButCreerCat.setText("Créer une catégorie");

        ButModifCat.setText("Modifier une catégorie");
        ButModifCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButModifCatActionPerformed(evt);
            }
        });

        ButSupCat.setText("Supprimer une catégorie");

        ButCreerSsCat.setText("Créer une sous-catégorie");
        ButCreerSsCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButCreerSsCatActionPerformed(evt);
            }
        });

        ButModifSsCat.setText("Modifier une sous-catégorie");
        ButModifSsCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButModifSsCatActionPerformed(evt);
            }
        });

        ButSupSsCat.setText("Supprimer une sous-catégorie");

        javax.swing.GroupLayout PannCreerModiSupprLayout = new javax.swing.GroupLayout(PannCreerModiSuppr);
        PannCreerModiSuppr.setLayout(PannCreerModiSupprLayout);
        PannCreerModiSupprLayout.setHorizontalGroup(
            PannCreerModiSupprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannCreerModiSupprLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(ButCreerSsCat)
                .addGap(33, 33, 33)
                .addComponent(ButModifSsCat)
                .addGap(18, 18, 18)
                .addComponent(ButSupSsCat)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannCreerModiSupprLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ButCreerCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButModifCat)
                .addGap(47, 47, 47)
                .addComponent(ButSupCat)
                .addGap(21, 21, 21))
        );
        PannCreerModiSupprLayout.setVerticalGroup(
            PannCreerModiSupprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PannCreerModiSupprLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(PannCreerModiSupprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCreerCat)
                    .addComponent(ButModifCat)
                    .addComponent(ButSupCat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PannCreerModiSupprLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButCreerSsCat)
                    .addComponent(ButModifSsCat)
                    .addComponent(ButSupSsCat))
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout PanResCatLayout = new javax.swing.GroupLayout(PanResCat);
        PanResCat.setLayout(PanResCatLayout);
        PanResCatLayout.setHorizontalGroup(
            PanResCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanResCatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PanResCatLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(PannCreerModiSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanResCatLayout.setVerticalGroup(
            PanResCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanResCatLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PannCreerModiSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelCatLayout = new javax.swing.GroupLayout(PanelCat);
        PanelCat.setLayout(PanelCatLayout);
        PanelCatLayout.setHorizontalGroup(
            PanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanSearchCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelCatLayout.createSequentialGroup()
                        .addComponent(lbl_cat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanResCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelCatLayout.setVerticalGroup(
            PanelCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanSearchCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(PanResCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(503, Short.MAX_VALUE))
        );

        tabPCPC.addTab("Catégories", PanelCat);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("ID Promotion :");

        jButton3.setText("Rechercher");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel6.setText("Pourcentage :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jButton3)
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_SearchPromo.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lbl_SearchPromo.setText("Rechercher une promotion");

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "idSolde", "pourcentage", "idProduit"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setText("ID Promotion :");

        jLabel8.setText("Pourcentage :");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jButton8.setText("Ajouter");

        jButton9.setText("Modifier");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Supprimer");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jButton9)
                .addGap(26, 26, 26)
                .addComponent(jButton10)
                .addGap(36, 36, 36))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelPromoLayout = new javax.swing.GroupLayout(PanelPromo);
        PanelPromo.setLayout(PanelPromoLayout);
        PanelPromoLayout.setHorizontalGroup(
            PanelPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPromoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelPromoLayout.createSequentialGroup()
                        .addComponent(lbl_SearchPromo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelPromoLayout.setVerticalGroup(
            PanelPromoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPromoLayout.createSequentialGroup()
                .addComponent(lbl_SearchPromo, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(556, Short.MAX_VALUE))
        );

        tabPCPC.addTab("Promotions", PanelPromo);

        lbl_cust.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        lbl_cust.setText("Rechercher un Client");

        PanSearchClient.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("ID Client :");

        jLabel2.setText("Nom :");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Prénom :");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Recherche");

        jButton2.setText("Effacer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setText("Supprimer un client");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanSearchClientLayout = new javax.swing.GroupLayout(PanSearchClient);
        PanSearchClient.setLayout(PanSearchClientLayout);
        PanSearchClientLayout.setHorizontalGroup(
            PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSearchClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanSearchClientLayout.createSequentialGroup()
                        .addGroup(PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanSearchClientLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(jTextField3)))
                            .addGroup(PanSearchClientLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        PanSearchClientLayout.setVerticalGroup(
            PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanSearchClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanSearchClientLayout.createSequentialGroup()
                        .addGroup(PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(PanSearchClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanSearchClientLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Telephone", "Adresse", "E-mail", "Commande", "Date", "Type", "Montant"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout PanelClientsLayout = new javax.swing.GroupLayout(PanelClients);
        PanelClients.setLayout(PanelClientsLayout);
        PanelClientsLayout.setHorizontalGroup(
            PanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanSearchClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelClientsLayout.createSequentialGroup()
                        .addComponent(lbl_cust)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelClientsLayout.setVerticalGroup(
            PanelClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_cust, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        tabPCPC.addTab("Clients", PanelClients);

        getContentPane().add(tabPCPC, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("Fichier");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMGestCat.setText("Gestion Catégories");
        jMGestCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestCatActionPerformed(evt);
            }
        });
        jMenu1.add(jMGestCat);

        jMGestProm.setText("Gestion des Promotions");
        jMenu1.add(jMGestProm);

        jMGestClient.setText("Gestion des Clients");
        jMenu1.add(jMGestClient);

        jMCharger.setText("Charger...");
        jMenu1.add(jMCharger);
        jMenu1.add(jSeparator2);

        jMSave.setText("Sauvegarder...");
        jMenu1.add(jMSave);
        jMenu1.add(jSeparator3);

        jMenuQuitter.setText("Quitter");
        jMenuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuQuitter);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("A propos ...");

        jMenuVersion.setText("Version");
        jMenuVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVersionActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuVersion);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SearchActionPerformed

    private void Radio_ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_ouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_ouiActionPerformed

    private void tf_prixReduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_prixReduitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_prixReduitActionPerformed

    private void Button_Search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Search1ActionPerformed

    private void Button_Search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Search2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_Search2ActionPerformed

    private void ButModifCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButModifCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButModifCatActionPerformed

    private void ButCreerSsCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButCreerSsCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButCreerSsCatActionPerformed

    private void ButModifSsCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButModifSsCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButModifSsCatActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButAddActionPerformed

    private void tf_fournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fournisseurActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMGestCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestCatActionPerformed

    }//GEN-LAST:event_jMGestCatActionPerformed

    private void cb_CatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CatActionPerformed
        cb_ssCat.removeAllItems();
        String cat = cb_Cat.getSelectedItem().toString();
        Object[] tabSsCat = CategorieProduit.getSsCategorie(cat).toArray();
        for(int i =0;i<tabSsCat.length;i++){
            cb_ssCat.addItem((String)tabSsCat[i]);       
        }
    }//GEN-LAST:event_cb_CatActionPerformed

    private void cb_ssCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ssCatActionPerformed

    }//GEN-LAST:event_cb_ssCatActionPerformed

    private void cb_ssCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_ssCatItemStateChanged
    }//GEN-LAST:event_cb_ssCatItemStateChanged
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuVersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVersionActionPerformed
         JOptionPane.showMessageDialog(this, "TP3 Java avancé, Elyes HADJ SALAH MAGRE - Alix BERNARDO", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuVersionActionPerformed

    private void jMenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitterActionPerformed
        int reply = JOptionPane.showConfirmDialog(this,"Voulez-vous vraiment quitter ?", "Attention", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuQuitterActionPerformed

    private void Button_effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_effacerActionPerformed
    }//GEN-LAST:event_Button_effacerActionPerformed

    private void Button_effacerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_effacerMouseClicked
        tf_Libelle.setText("");
        cb_Cat.setSelectedIndex(0);
        cb_ssCat.setSelectedIndex(0);
    }//GEN-LAST:event_Button_effacerMouseClicked

    private void cb_CatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_CatItemStateChanged
        
    }//GEN-LAST:event_cb_CatItemStateChanged

    private void cb_CategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_CategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_CategActionPerformed

    private void cb_CategItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_CategItemStateChanged
 
    }//GEN-LAST:event_cb_CategItemStateChanged

    private void Button_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SearchMouseClicked
        
        PanResult.setVisible(true);
        ta_description.enable(false);
        for (Component c : PanResult.getComponents()){
            c.setEnabled(false);
        }    
    }//GEN-LAST:event_Button_SearchMouseClicked

    private void cb_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_catActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButAddMouseClicked
        PanResult.setVisible(true); 
        for (Component c : PanResult.getComponents()){
            c.setEnabled(true);
        }    
        tf_ID.enable(false);
    }//GEN-LAST:event_jButAddMouseClicked

    private void tf_ImageCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ImageCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ImageCatActionPerformed

    private void tf_ImageSsCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ImageSsCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ImageSsCatActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {      
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IHM_Catalogue().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButCreerCat;
    private javax.swing.JButton ButCreerSsCat;
    private javax.swing.JButton ButModifCat;
    private javax.swing.JButton ButModifSsCat;
    private javax.swing.JButton ButSupCat;
    private javax.swing.JButton ButSupSsCat;
    private javax.swing.JButton Button_Search;
    private javax.swing.JButton Button_Search1;
    private javax.swing.JButton Button_Search2;
    private javax.swing.JButton Button_effacer;
    private javax.swing.JButton Button_effacer1;
    private javax.swing.JButton Button_effacer2;
    private javax.swing.JPanel PanResCat;
    private javax.swing.JPanel PanResult;
    private javax.swing.JPanel PanSearch;
    private javax.swing.JPanel PanSearchCat;
    private javax.swing.JPanel PanSearchClient;
    private javax.swing.JPanel PanelCat;
    private javax.swing.JPanel PanelClients;
    private javax.swing.JPanel PanelProduits;
    private javax.swing.JPanel PanelPromo;
    private javax.swing.JPanel PannButtonSearch;
    private javax.swing.JPanel PannButtonSearch1;
    private javax.swing.JPanel PannCreerModiSuppr;
    private javax.swing.JRadioButton Radio_non;
    private javax.swing.JRadioButton Radio_oui;
    private javax.swing.JScrollPane Scroll_description;
    private javax.swing.JTable TableauCat;
    private javax.swing.JComboBox<String> cb_Cat;
    private javax.swing.JComboBox<String> cb_Categ;
    private javax.swing.JComboBox<String> cb_cat;
    private javax.swing.JComboBox<String> cb_ssCat;
    private javax.swing.JComboBox<String> cb_ssCat1;
    private javax.swing.JComboBox<String> cb_ssCateg;
    private javax.swing.JButton jButAdd;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMCharger;
    private javax.swing.JMenuItem jMGestCat;
    private javax.swing.JMenuItem jMGestClient;
    private javax.swing.JMenuItem jMGestProm;
    private javax.swing.JMenuItem jMSave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuQuitter;
    private javax.swing.JMenuItem jMenuVersion;
    private javax.swing.JPanel jPanAjouter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lbl_Cat;
    private javax.swing.JLabel lbl_Cate;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JPanel lbl_ImageCat;
    private javax.swing.JLabel lbl_ImageSsCat;
    private javax.swing.JLabel lbl_Libelle;
    private javax.swing.JLabel lbl_Marque;
    private javax.swing.JLabel lbl_Search;
    private javax.swing.JLabel lbl_SearchPromo;
    private javax.swing.JLabel lbl_alerte;
    private javax.swing.JLabel lbl_cat;
    private javax.swing.JLabel lbl_categ;
    private javax.swing.JLabel lbl_cust;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_prix;
    private javax.swing.JLabel lbl_prix_Reduit;
    private javax.swing.JLabel lbl_prod;
    private javax.swing.JLabel lbl_promo;
    private javax.swing.JLabel lbl_ssCat;
    private javax.swing.JLabel lbl_ssCat1;
    private javax.swing.JLabel lbl_ssCateg;
    private javax.swing.JLabel lbl_stock;
    private javax.swing.JTextArea ta_description;
    private javax.swing.JTabbedPane tabPCPC;
    private javax.swing.JTextField tf_ID;
    private java.awt.TextField tf_ImageCat;
    private java.awt.TextField tf_ImageSsCat;
    private javax.swing.JTextField tf_Libelle;
    private javax.swing.JTextField tf_Marque;
    private javax.swing.JTextField tf_alerte;
    private javax.swing.JTextField tf_fournisseur;
    private javax.swing.JTextField tf_prix;
    private javax.swing.JTextField tf_prixReduit;
    private javax.swing.JTextField tf_prod;
    private javax.swing.JTextField tf_stock;
    // End of variables declaration//GEN-END:variables
}